/**
 * @author Rhonda Marshall
 * Nov 9, 2015
 * 
 * The Loaded class implements the Die interface
 
 */
package dnddiceroller;

import java.util.Random;

/**
 *
 * @author Rhonda Marshall
 * Nov 9, 2015
 */

public class Loaded implements Die {
    private int numberOfSides;             // number of sides on the dice
    private int value;                     // value generated by a random number 
    private int loadedSide;                // the loaded side of the dice
    
    /**
     * Constructor
     * @param numberOfSides     The numberOfSides on the dice
     * @param loadedSide        The side of the dice that is loaded
     */
    public Loaded(int numberOfSides, int loadedSide) {
        this.numberOfSides = numberOfSides;
        this.value = 0;
        this.loadedSide = loadedSide;
    } // Loaded constructor
    
    /**
     * The roll method (Required by Die interface)
     * The random number number will determine the face of the dice that
     * lands down
     * 
     * The random number will be a value between 1 and the numberOfSides
     * If the random number is greater than 50% of the numberofSides, the die
     * value will be the loaded die otherwise the die value will be the random
     * number
     * 
     * This is a 50% probability the dice will land on the loaded side
     * 
     */
    @Override
    public void roll() {
        Random randomNumber = new Random();
        this.value = randomNumber.nextInt(this.numberOfSides) + 1;
        
        int low = (int)((this.numberOfSides/2) + 1);
        int high = this.numberOfSides;
        if (this.value >= low && this.value <= high)
            this.value = this.getLoadedSide();
          
    } // roll method
    
    
    /**
     * getValue accessor method (Required by Die interface)
     * @return  The Loaded objects value
     */
    @Override
    public int getValue(){
        return this.value;
    } // getValue method
    
    /**
     * getLoadedSide accessor method
     * @return Loaded objects loadedSide
     */
    private int getLoadedSide() {
        return this.loadedSide;
    } // getLoadedSide method
    
} // LoadedDie class

  
       
