package dnddiceroller;

import java.util.Random;

/**
 * @author Rhonda Marshall
 * Nov 9, 2015
 * 
 * The NumberedDie class implements the Die interface
 
 */
public class NumberedDie implements Die {
    private int numberOfSides;             // number of sides on the dice
    private int value;                     // value generated by a random number 
    
    /**
     * Constructor
     * @param numberOfSides
     */
    public NumberedDie(int numberOfSides) {
        this.numberOfSides = numberOfSides;
        this.value = 0;
    } // NumberedDie constructor
    
    /**
     * The roll method (Required by Die interface)
     * Sets the value field equal to random number between 1 and the numberOfSides
     */
    @Override
    public void roll() {
        Random randomNumber = new Random();
        this.value = randomNumber.nextInt(this.numberOfSides) + 1; 
        
    } // roll method
    
    /**
     * getValue accessors method (Required by Die interface)
     * @return  The NumberedDie objects value
     */
    @Override
    public int getValue(){
        return this.value;
    } // getValue method
       
} // NumberedDie class

